import os

def split_sql(filename, chunk_size=10000): # 10KB chunks for safe reading
    with open(filename, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Helper to clean up SQL file reading
    # We split by 'INSERT INTO' but need to be careful.
    # The file structure is: INSERT INTO ...;\nINSERT INTO ...
    # So splitting on ";\nINSERT" might work, but the first one is just "INSERT".
    
    # Better: regex split? Or just reading line by line and grouping?
    # Since specific format is generated by us: 
    # f"INSERT INTO ... );\n"
    
    statements = []
    current_stmt = []
    
    lines = content.splitlines(keepends=True)
    for line in lines:
        current_stmt.append(line)
        if line.strip().endswith(");"):
            statements.append("".join(current_stmt))
            current_stmt = []
            
    if current_stmt:
        statements.append("".join(current_stmt))
        
    chunks = []
    current_chunk = []
    current_size = 0
    
    for stmt in statements:
        if not stmt.strip(): continue
        
        if current_size + len(stmt) > chunk_size and current_chunk:
            chunks.append("".join(current_chunk))
            current_chunk = []
            current_size = 0
        
        current_chunk.append(stmt)
        current_size += len(stmt)
        
    if current_chunk:
        chunks.append("".join(current_chunk))
        
    for i, chunk in enumerate(chunks):
        out_name = f"sql_chunk_{i}.sql"
        with open(out_name, 'w', encoding='utf-8') as f:
            f.write(chunk)
        print(f"Created {out_name} ({len(chunk)} chars)")

if __name__ == "__main__":
    split_sql("insert_rules.sql")
